### ISSUE TITLE
Compatibility with Relay mutations

### ISSUE THREAD

**Issue by andrewtmendoza** [tOgg1/graphene-django-cud#63]
Hi @tOgg1, is graphene-django-cud compatible with Relay mutations? https://docs.graphene-python.org/projects/django/en/latest/mutations/#relay

Thanks!

**Comment by tOgg1** [comment]
Hey @andrewtmendoza.

Pardon the delayed response. When you mean compatible, what exactly would you like to see/how would you want to use the library?

There is currently no option to make the library create mutations that inherit from relay.ClientIDMutation instead of directly from the regular Mutation.

**Comment by tOgg1** [comment]
Closing until further information is provided.

**Comment by NwawelAIroume** [comment]
@tOgg1 sorry it is the wrong issue number mentioned could you remove this?
thanks
