### ISSUE TITLE
End of life

### ISSUE THREAD

**Issue by tOgg1** [tOgg1/graphene-django-cud#99]
[Graphene-django is now EOL](https://github.com/graphql-python/graphene-django/issues/1324).

Hence, it makes no sense to continue developing this library. The general recommendation in the community seems to be switching to [Strawberry](https://github.com/strawberry-graphql/strawberry).

Both myself and the [Ur Solutions team](https://github.com/Ur-Solutions) will continue fixing critical bugs for this library in the foreseeable.

**Comment by zigomir** [comment]
What about https://github.com/graphql-python/graphene-django/releases/tag/v3.0.0?

**Comment by calummackervoy** [comment]
Yeah from latter comments on the issue linked, recent releases, commits etc I believe that `graphene-django` has come back to life

**Comment by jyoost** [comment]
definitely!! and graphen-django-cud ROCKS!

**Comment by sjdemartini** [comment]
@tOgg1 Would you consider adding anyone else as a maintainer on this project? `graphene-django` went idle, but has come back and is being actively maintained by a new set of folks (myself included), and `graphene-django-cud` is a fantastic part of the `graphene-django` ecosystem. I'd be happy to help however I can, if you're willing.

Or personally, I'd benefit from at least a final patch version release that includes this already-merged change https://github.com/tOgg1/graphene-django-cud/pull/85, since we found that to be polluting our app's logs.

Thanks for considering!

**Comment by tOgg1** [comment]
Hi guys!

Thanks for the feedback and bumps.

Yeah, we will start maintaining this again shortly. Pardon the delay. 

Expect a new release with some minor QoL updates before July 1st.
